<?xml version='1.0' encoding='UTF-8'?>
<package format="2">
  <name>voxblox</name>
  <version>0.0.0</version>
  <description>Voxblox</description>
  <maintainer email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</maintainer>
  <maintainer email="marius.fehr@mavt.ethz.ch">Marius Fehr</maintainer>
  <license>BSD</license>
  <author email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</author>
  <author email="marius.fehr@mavt.ethz.ch">Marius Fehr</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>eigen</depend>
  <depend>eigen3_cmake_module</depend>
  <depend>libgflags-dev</depend>
  <depend>libgoogle-glog-dev</depend>
  <depend>minkindr</depend>
  <depend>protobuf</depend>
  <depend>rosidl_default_generators</depend>
  <depend>voxblox_proto</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
